version: '3'

services:
  db:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - type: bind
        source: ./db
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: demo
      TZ: Asia/Tokyo