name: SpringBoot CI with Gradle

# mainブランチへのpushで実行する
on: 
  push:
    branches: [ "main" ]

# リポジトリの権限
permissions:
  contents: read

# ジョブの実行
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: restapi
    
    steps:
      # リポジトリのチェックアウト
      - uses: actions/checkout@v3
      # JDKのセットアップ
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      # Gradleのバッチに実行権限を付与する
      - name: Make Gradle executable
        run: chmod +x ./gradlew
      # dbディレクトリの作成
      - name: Create db directory
        run: mkdir db
      # dockerコンテナを立ち上げる
      - name: Run docker-compose
        run: docker-compose up -d
      # ビルド
      - name: Build with Gradle
        run: ./gradlew build
