name: SpringBoot CI with Gradle

# mainブランチへのpushで実行する
on: 
  push:
    branches: [ "main", "develop"]

# リポジトリの権限
permissions:
  contents: read

# ジョブの実行
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: restapi
    
    steps:
      # リポジトリのチェックアウト
      - uses: actions/checkout@v3
      # JDKのセットアップ
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      # SonarCloudのキャッシュ 
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      # Gradleのバッチに実行権限を付与する
      - name: Make Gradle executable
        run: chmod +x ./gradlew
      # dbディレクトリの作成
      - name: Create db directory
        run: mkdir db
      # dockerコンテナを立ち上げる
      - name: Run docker-compose
        run: docker-compose up -d
      # ビルド
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew build sonar --info
